
server:
  port: 8888

spring:
  application:
    name: zicai-config-jooq

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    sql-script-encoding: utf-8
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:config_jooq_test
    username: test
    password: test
  h2:
    console:
      enabled: true
      path: /h2
  jooq:
    sql-dialect: h2

logging:
  level:
    root: info
    org.jooq: debug
