
server:
  port: 8888

spring:
  application:
    name: zicai-config-server

  cloud:
    config:
      discovery:
        enabled: true
        service-id: ${spring.application.name}

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    sql-script-encoding: utf-8
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:config_server_test
    username: test
    password: test
  h2:
    console:
      enabled: true
      path: /h2

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: io.gitee.zicai.core.entity
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  not-empty: false
#pagehelper:
#  helper-dialect: MYSQL

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    appname: ${spring.application.name}
    instance-id: ${spring.application.name}:${random.int(10000,50000)}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
