
server:
  port: 8888

spring:
  application:
    name: zicai-config-server

  cloud:
    config:
      discovery:
        enabled: true
        service-id: ${spring.application.name}

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    sql-script-encoding: utf-8
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:config_server_test
    username: test
    password: test
  h2:
    console:
      enabled: true
      path: /h2

mybatis-plus:
  mapper-locations: classpath:/mappers/*.xml
  #实体扫描 多个package用逗号或者分号分隔
  typeAliasesPackage: io.gitee.zicai.core.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    lazy-loading-enabled: false
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: true
    auto-mapping-behavior: partial
    default-statement-timeout: 20
    default-executor-type: simple
    jdbc-type-for-null: null

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    appname: ${spring.application.name}
    instance-id: ${spring.application.name}:${random.int(10000,50000)}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
